# generated by fastapi-codegen:
#   filename:  myopenapi.json
#   timestamp: 2024-05-17T06:25:45+00:00

from __future__ import annotations

from typing import List, Optional

from pydantic import BaseModel, Field


class MapfSendTaskPostRequestTaskItem(BaseModel):
    task_id: Optional[str] = Field(None, example="7235686cd3")
    robot_id: str = Field(None, example="agv_1")
    start_location: str = Field(None, example="wp1")
    goal_location: str = Field(None, example="wp1")


class MapfSendTaskPostRequestItem(BaseModel):
    tasks: List[MapfSendTaskPostRequestTaskItem]


class ReplaceDestination(BaseModel):
    task_id: Optional[str] = Field(None, example='7235686cd3')
    robot_id: str = Field(None, example='agv_1')
    goal_location: str = Field(None, example='wp1')

class MapfReplaceDestinationPostRequestItem(BaseModel):
    destinations: List[ReplaceDestination]


class MapfPauseTaskPutRequestItem(BaseModel):
    task_id: Optional[str] = Field(None, example="7235686cd3")


class MapfResumeTaskPutRequestItem(BaseModel):
    task_id: Optional[str] = Field(None, example="7235686cd3")


class MapfCancelTaskPostRequestItem(BaseModel):
    task_id: Optional[str] = Field(None, example="7235686cd3")
